project.godot
=> [fix] project.godot

scenes/sokoban/box.tscn, scenes/sokoban/gravity_1.tscn, scenes/sokoban/level-0.tscn, scripts/sokoban/basic_button.gd, scripts/sokoban/bullet.gd
[feat]  
射出去的子弹，如果碰到tilemaplayer 现在会自动放置一个重力区域
展示关卡，玩家在天花板上放置一个重力区域吸引box踩到天花板上的按钮过关
* TODO: 慢点拓展到多方向
=> [feat] bullet can place a gravity area

scenes/sokoban/gravity_1.tscn, scenes/sokoban/level-0.tscn, scripts/sokoban/bullet.gd
=> [fix] gravity area

scenes/sokoban/player_with_gravity_gun.tscn, scripts/sokoban/player_with_gravity_gun.gd
=> [fix] flip when player in gravity

scenes/sokoban/bullet.tscn, scenes/sokoban/player_with_gravity_gun.tscn, scripts/sokoban/player_with_gravity_gun.gd
fix
修复人物发射子弹会和子弹碰撞的问题
修复人物在移动平台上发子弹会掉下去的问题
=> [fix] jump on platform

scenes/modules/kill_zone.tscn, scripts/modules/kill_zone.gd
=> [feat] death anime

scripts/singleton/consts.gd, scripts/sokoban/player_with_gravity_gun.gd
=> [fix] add max speed in different gravity

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] wasd shoot

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] big jump

scenes/sokoban/player_with_gravity_gun.tscn, scripts/sokoban/basic_box.gd, scripts/sokoban/player_with_gravity_gun.gd
=> [fix] push box

project.godot, scenes/sokoban/chasing_slime.tscn, scenes/sokoban/level-01/level-01-chasing.tscn, scripts/sokoban/chasing_slime.gd
=> [feat] chasing demo

scenes/sokoban/level-01/level-01-chasing.tscn, scenes/sokoban/shooting_slime.tscn, scripts/sokoban/shooting_slime.gd
=> [feat] moving slime and shooting bullets

scenes/sokoban/level-01/level-01-chasing.tscn, scripts/sokoban/basic_button.gd
=> [fix] button can control multiple scenes

scripts/sokoban/bullet.gd
fix
现在子弹打到box(characterbody2D)上会直接消失
=> [fix] bullet will disappear when hit box

scenes/sokoban/gravity_1.tscn
=> [fix] gravity line alpha=0

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] player up when up push box

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] double jump err if die

scripts/sokoban/bullet.gd, scripts/sokoban/player_with_gravity_gun.gd
=> [feat] ammo

scripts/singleton/game_manager.gd, scripts/sokoban/player_with_gravity_gun.gd
二段跳开启关闭加入game manager，调用 `func set_skill_enabled(skill_name: StringName, value: bool) -> void:` 打开或关闭
=> [feat] second jump enable/disable in game manager

scripts/sokoban/qte_gravity_area.gd
=> [feat] draw qte gravity area

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] change on terrain judege raycast

scripts/sokoban/player_with_gravity_gun.gd
fix
修复玩家可以爬墙，修复会掉入重力井逃课
减少player raycast offset
=> [fix] fix player can climbing walls, fix  raycast offset

scripts/sokoban/player_with_gravity_gun.gd
fix
coyate time, 在离开平台之后0.2s内还能跳跃，更加宽容的起跳
=> [fix] coyate time to tolerate more on leaving platform

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] can use coyote time more than once

scripts/sokoban/player_with_gravity_gun.gd
修改角色移动/跳跃：
* 修改 is_on_terrain()
* 修改预输入
* 修改起跳加速方式
#TODO: 修改跳跃高度，大小跳
=> [fix] on floor, pre input, run

scripts/singleton/consts.gd, scripts/sokoban/player_with_gravity_gun.gd
=> [fix] improve jump part-1

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] add x speed when jump

scripts/sokoban/player_with_gravity_gun.gd
增加了corner correct，跳跃的时候如果碰到平台将将差一点，会调整角色位置，让他擦过去
=> [fix] add corner correct when in air

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] add gravity muliplier when fall

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] gun shoot pos

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] second jump

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] coyote time and scond jump conflict

scripts/sokoban/player_with_gravity_gun.gd
=> [fix] hook hit wall

scenes/sokoban/player_with_gravity_gun.tscn, scenes/sokoban/shadow.tscn, scripts/sokoban/player_with_gravity_gun.gd, scripts/sokoban/shadow.gd
=> [feat] hook shadow

scenes/sokoban/hook_1.tscn, scenes/sokoban/player_with_gravity_gun.tscn, scripts/sokoban/hook_1.gd, scripts/sokoban/player_with_gravity_gun.gd
=> [feat] hook v2

scenes/sokoban/destruct_01.tscn, scenes/sokoban/season-2-examples/01-more-on-platforms.tscn, scripts/sokoban/destruct_obj.gd
=> fix destructible object

scenes/sokoban/player_with_gravity_gun.tscn, scenes/sokoban/season-2-examples/01-more-on-platforms.tscn, scripts/sokoban/destruct_obj.gd, scripts/sokoban/player_with_gravity_gun.gd
=> feat hook destruct

scenes/sokoban/destruct_obj.tscn, scenes/sokoban/season-2-examples/01-more-on-platforms.tscn, scenes/sokoban/season-2-examples/test_destruct.tscn, scripts/sokoban/destruct_obj.gd
优化 destruct obj, 可以把sprite2d传参
=> fix destruct sprite 2d

scenes/sokoban/test_chase/chase_fake.gd, scenes/sokoban/test_chase/chase_fake.tscn
=> feat beginning camera pan of chase fake

scripts/sokoban/player_with_gravity_gun.gd
=> fix box on head global pos

scripts/sokoban/destruct_obj.gd
=> fix destruct obj casuse lagging
